# -*- coding: utf-8 -*-
"""Tic Tac Toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dm_XZEOfHPgfq-eYX3UCeQJh8oeahyDo
"""

theBoard = {'1': ' ' , '2': ' ' , '3': ' ' ,
            '4': ' ' , '5': ' ' , '6': ' ' ,
            '7': ' ' , '8': ' ' , '9': ' ' }

board_keys = []

for key in theBoard:
    board_keys.append(key)

def printBoard(board):
    print(board['1'] + '|' + board['2'] + '|' + board['3'])
    print('-+-+-')
    print(board['4'] + '|' + board['5'] + '|' + board['6'])
    print('-+-+-')
    print(board['7'] + '|' + board['8'] + '|' + board['9'])

def game():

    turn = 'X'
    count = 0


    for i in range(10):
        printBoard(theBoard)
        print("It's your turn," + turn + ".Which place do you want to move to?")

        move = input()        

        if theBoard[move] == ' ':
            theBoard[move] = turn
            count += 1
        else:
            print("That place is already filled.\nMove to which place?")
            continue

        if count >= 5:
            if theBoard['7'] == theBoard['8'] == theBoard['9'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")                
                break
            elif theBoard['4'] == theBoard['5'] == theBoard['6'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break
            elif theBoard['1'] == theBoard['2'] == theBoard['3'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break
            elif theBoard['1'] == theBoard['4'] == theBoard['7'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break
            elif theBoard['2'] == theBoard['5'] == theBoard['8'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break
            elif theBoard['3'] == theBoard['6'] == theBoard['9'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break 
            elif theBoard['7'] == theBoard['5'] == theBoard['3'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break
            elif theBoard['1'] == theBoard['5'] == theBoard['9'] != ' ': 
                printBoard(theBoard)
                print("Game Over.")                
                print(" **** " +turn + " won. ****")
                break 

        if count == 9:
            print("!!!Game Over!!!")                
            print("It's a Tie!!")

        if turn =='X':
            turn = 'O'
        else:
            turn = 'X'        
    

game()

theBoard = {'1': ' ' , '2': ' ' , '3': ' ' ,
            '4': ' ' , '5': ' ' , '6': ' ' ,
            '7': ' ' , '8': ' ' , '9': ' ' }

board_keys = []
for key in theBoard:
    board_keys.append(key)

def printBoard(board):
    print(board['1'] + '|' + board['2'] + '|' + board['3'])
    print('-+-+-')
    print(board['4'] + '|' + board['5'] + '|' + board['6'])
    print('-+-+-')
    print(board['7'] + '|' + board['8'] + '|' + board['9'])

row_1 = board[1] + board[2] + board[3]
row_2 = board[4] + board[5] + board[6]
row_3 = board[7] + board[8] + board[9]
def game():

    turn = 'X'
    count = 0


    for i in range(10):
        printBoard(theBoard)
        print("It's your turn," + turn + ".Which place do you want to move to?")

        move = input()        

        if theBoard[move] == ' ':
            theBoard[move] = turn
            count += 1
            if turn =='X':
              turn = 'O'
            else:
              turn = 'X'
        else:
            print("That place is already filled.\nMove to which place?")
            continue
game()
def row_win():
  for i in range(10):
      if count >= 5:
          if row_3 == (f"{turn} {turn} {turn}") : 
              printBoard(theBoard)
              print("Game Over.")                
              print(" **** " +turn + " won. ****")                
              break
          if row_2 == (f"{turn} {turn} {turn}"): 
              printBoard(theBoard)
              print("Game Over.")                
              print(" **** " +turn + " won. ****")
              break
          if row_1 == (f"{turn} {turn} {turn}"):
              printBoard(theBoard)
              print("Game Over.")                
              print(" **** " +turn + " won. ****")
              break
row_win()          
def column_win():
  for i in range(10):    
    if count >= 5:        
        if theBoard['1'] == theBoard['4'] == theBoard['7'] != ' ': 
            printBoard(theBoard)
            print("Game Over.")                
            print(" **** " +turn + " won. ****")
            break
        elif theBoard['2'] == theBoard['5'] == theBoard['8'] != ' ': 
            printBoard(theBoard)
            print("Game Over.")                
            print(" **** " +turn + " won. ****")
            break
        elif theBoard['3'] == theBoard['6'] == theBoard['9'] != ' ': 
            printBoard(theBoard)
            print("Game Over.")                
            print(" **** " +turn + " won. ****")
            break 
column_win()
      
def diagonal_win():      
  for i in range(10):
    if count >= 5:     
      if theBoard['7'] == theBoard['5'] == theBoard['3'] != ' ': 
          printBoard(theBoard)
          print("Game Over.")                
          print(" **** " +turn + " won. ****")
          break
      elif theBoard['1'] == theBoard['5'] == theBoard['9'] != ' ': 
               printBoard(theBoard)
               print("Game Over.")                
               print(" **** " +turn + " won. ****")
               break 
diagonal_win()

def tie():
  if count == 9:
    print("!!!Game Over!!!")                
    print("It's a Tie!!")

tie()

def check_if_game_over():
    global winner
    global game_still_going
    if theBoard['7'] == theBoard['8'] == theBoard['9'] != ' ': 
      printBoard(theBoard)
      winner=current_player           
      game_still_going
    elif theBoard['4'] == theBoard['5'] == theBoard['6'] != ' ': 
      printBoard(theBoard)
       print(" **** " +current_player+ " won. ****")
      
    elif theBoard['1'] == theBoard['2'] == theBoard['3'] != ' ': 
      printBoard(theBoard)
      
      
    elif theBoard['1'] == theBoard['4'] == theBoard['7'] != ' ': 
      printBoard(theBoard)
      print("Game Over.")                
      print(" **** " +current_player + " won. ****")

    elif theBoard['2'] == theBoard['5'] == theBoard['8'] != ' ': 
      printBoard(theBoard)
      print("Game Over.")                
      print(" **** " +current_player + " won. ****")

    elif theBoard['3'] == theBoard['6'] == theBoard['9'] != ' ': 
      printBoard(theBoard)
      print("Game Over.")                
      print(" **** " +current_player + " won. ****")